# SYNTAX THEME
# modifiers:
# # - bold
# - dim
# - italic
# - slow_blink
# - rapid_blink
# - reversed
# - hidden
# - crossed_out

# underline:
# - style
#   - line
#   - curl
#   - dashed
#   - dotted
#   - double_line
# - color

"string" = { fg = "important_local", modifiers = ["italic"] }
"comment" = { fg = "important_global", modifiers = ["bold"] }
"comment.block.documentation" = { fg = "minor", modifiers = ["dim"] }
"punctuation" = { fg = "minor" }
"keyword" = { fg = "minor" }
"keyword.control.return" = { modifiers = ["bold"], underline.style = "line" }
"keyword.control.exception" = { modifiers = ["bold"], underline.style = "line" }
"operator" = { fg = "minor" }

"program.import_declaration.import" = { fg = "debug" }

"markup.heading" = { fg = "important_global", modifiers = ["bold"] }
"markup.list" = "minor"
"markup.bold" = { fg = "normal", modifiers = ["bold"] }
"markup.italic" = { fg = "normal", modifiers = ["italic"] }
"markup.link.url" = "focus"
"markup.link.text" = "important_local"
"markup.link.label" = "important_global"
"markup.quote" = { fg = "important_local", modifiers = ["italic"] }
"markup.raw.inline" = { fg = "important_local" }
"markup.raw.block" = { fg = "important_global" }

"diff.plus" = { fg = "important_local", modifiers = ["bold"] }
"diff.delta" = { fg = "ui_minor" }
"diff.minus" = { fg = "minor", modifiers = ["crossed_out"] }

# UI THEME
"ui.background" = { bg = "backdrop" }

"ui.cursor" = { bg = "accent" }
"ui.cursor.primary" = { bg = "accent" }
"ui.cursor.insert" = { bg = "ui_accent" }
"ui.cursor.select" = { bg = "ui_accent" }
"ui.cursor.match" = { fg = "ui_important_global", modifiers = ["slow_blink"] }

"ui.selection" = { bg = "ui_minor" }
"ui.selection.primary" = { bg = "ui_focus" }

"ui.linenr" = { fg = "ui_unfocus" }
"ui.linenr.selected" = { fg = "ui_minor" }

"ui.statusline" = { fg = "ui_minor", bg = "ui_backdrop" }
"ui.statusline.inactive" = { fg = "ui_unfocus", bg = "ui_backdrop" }

# space between buffers
"ui.window" = { fg = "ui_minor", bg = "ui_backdrop" }

# help text box above command input
"ui.help" = { fg = "ui_minor", bg = "ui_backdrop" }

# focused item in file picker
"ui.text.focus" = { fg = "ui_focus" }

"ui.menu.selected" = { fg = "ui_important", underline.style = "double_line" }

# selected line in buffer picker
"ui.highlight" = { bg = "ui_focus" }

"ui.virtual.ruler" = { fg = "ui_unfocus", bg = "ui_backdrop" }
"ui.virtual.whitespace" = { fg = "ui_unfocus" }

"warning" = { bg = "warning" }
"error" = { bg = "error" }
"info" = { bg = "info" }
"hint" = { fg = "info", modifiers = ["dim"] }

[palette]

# this is an incomplete stub file
# the palette should be appended to create a valid helix theme
