# SYNTAX THEME
# modifiers:
# # - bold
# - dim
# - italic
# - slow_blink
# - rapid_blink
# - reversed
# - hidden
# - crossed_out

# underline:
# - style
#   - line
#   - curl
#   - dashed
#   - dotted
#   - double_line
# - color

"comment" = { fg = "important_global", modifiers = ["bold"] }
"string" = { fg = "important_local", modifiers = ["italic"] }
"comment.block.documentation" = { fg = "minor", modifiers = ["dim"] }
"punctuation" = { fg = "minor" }
"keyword" = { fg = "minor" }
"tag" = { fg = "minor" }
"keyword.control.return" = { modifiers = ["bold"], underline.style = "line" }
"keyword.control.exception" = { modifiers = ["bold"], underline.style = "line" }
"operator" = { fg = "minor" }
"variable.parameter" = { fg = "focus", modifiers = ["bold"] }

"markup.heading" = { fg = "important_global", modifiers = [
  "bold",
], underline.style = "double_line" }
"markup.heading.marker" = { fg = "minor" }
"markup.list" = "minor"
"markup.bold" = { modifiers = ["bold"] }
"markup.italic" = { modifiers = ["italic"] }
"markup.strikethrough" = { modifiers = ["crossed_out"] }
"markup.link.url" = "accent"
"markup.link.text" = "important_local"
"markup.link.label" = "important_global"
"markup.quote" = { fg = "important_local", modifiers = ["italic"] }
"markup.raw.inline" = { fg = "important_local" }
"markup.raw.block" = { fg = "important_global" }

"diff.plus" = { fg = "important_local", modifiers = ["bold"] }
"diff.delta" = { fg = "unfocus" }
"diff.minus" = { fg = "focus", modifiers = ["crossed_out"] }

"ui.background" = { fg = "normal", bg = "backdrop" }
"ui.background.separator" = { fg = "ui_minor" }

"ui.cursor" = { fg = "normal", bg = "accent" }
"ui.cursor.primary" = { fg = "normal", bg = "accent" }
"ui.cursor.match" = { fg = "normal", bg = "unfocus", modifiers = [
  "slow_blink",
] }

"ui.cursorline.primary" = { bg = "debug" }

"ui.selection" = { fg = "normal", bg = "ui_important_local" }
"ui.selection.primary" = { fg = "normal", bg = "ui_important_global" }

"ui.linenr" = { fg = "ui_unfocus" }
"ui.linenr.selected" = { fg = "ui_accent" }

"ui.statusline" = { fg = "ui_minor", bg = "ui_backdrop" }
"ui.statusline.separator" = { fg = "ui_unfocus", bg = "ui_backdrop" }
"ui.statusline.insert" = { fg = "ui_important_global", modifiers = ["bold"] }
"ui.statusline.select" = { fg = "ui_focus", modifiers = ["bold"] }
"ui.statusline.inactive" = { fg = "ui_unfocus", bg = "ui_backdrop" }

"ui.bufferline" = { fg = "ui_minor", bg = "ui_backdrop" }
"ui.bufferline.active" = { fg = "ui_important_global", bg = "ui_unfocus", modifiers = [
  "bold",
], underline = { style = "double_line", color = "ui_backdrop" } }

"ui.gutter" = { bg = "ui_backdrop" }

"ui.debug.breakpoint" = { fg = "ui_important_global" }
"ui.debug.active" = { fg = "ui_important_global" }

"ui.window" = { fg = "ui_unfocus", bg = "ui_backdrop" }

"ui.help" = { fg = "ui_important_global", bg = "ui_backdrop" }

"ui.text" = { fg = "normal", bg = "backdrop" }
"ui.text.focus" = { fg = "ui_focus" }
"ui.text.info" = { fg = "ui_normal", bg = "ui_backdrop" }
"ui.text.inactive" = { fg = "ui_minor" }

"ui.menu" = { fg = "ui_normal", bg = "ui_backdrop" }
"ui.menu.selected" = { fg = "ui_focus", bg = "ui_backdrop", modifiers = [
  "bold",
] }
"ui.menu.scroll" = { fg = "ui_accent", bg = "ui_backdrop" }

"ui.popup" = { fg = "normal", bg = "backdrop" }
"ui.popup.info" = { fg = "ui_minor", bg = "ui_backdrop" }

"ui.highlight" = { bg = "ui_focus" }
"ui.highlight.frameline" = { bg = "ui_important_global" }

"ui.virtual.ruler" = { bg = "ui_unfocus" }
"ui.virtual.whitespace" = { fg = "ui_unfocus" }
"ui.virtual.inlay-hint" = { fg = "ui_minor" }

"error" = { bg = "error" }
"warning" = { bg = "warning" }
"info" = { bg = "info" }
"hint" = { fg = "info", modifiers = ["dim"] }
"diagnostic.error" = { underline = { style = "double_line", color = "error" } }
"diagnostic.warning" = { underline = { style = "double_line", color = "warning" } }
"diagnostic.info" = { underline = { style = "double_line", color = "info" } }
"diagnostic.hint" = { underline = { style = "double_line", color = "info" }, modifiers = [
  "dim",
] }
"special" = { fg = "debug" }

[palette]

# this is an incomplete stub file
# the palette should be appended to create a valid helix theme
